x = float(input("NUMBER :"))
y = float(input("NUMBER :"))
print("---------------------")
print(x,"+",y,"=",x+y)
print(x,"-",y,"=",x-y)
print(x,"*",y,"=",x*y)
print(x,"/",y,"=",x/y)
print("---------------------")